apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
       containers:
         - name: medicure
           image: hameedn/health_care:3.0
           ports:
             - containerPort: 8082
               name: http-web-app-01
